# Generated by Django 4.0.3 on 2022-03-21 05:10

import datetime
from django.db import migrations, models
import tlog.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogUploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=10, verbose_name='作者')),
                ('author_role', models.CharField(choices=[('Coach', '教练'), ('Competitor', '选手'), ('Student', '学生')], default='Competitor', max_length=10, verbose_name='角色')),
                ('log_date', models.DateField(default=datetime.date.today, verbose_name='日期')),
                ('class_type', models.CharField(choices=[('CL', '精英班'), ('TR', '中国集训队')], default='TR', max_length=100, verbose_name='班级')),
                ('log_file', models.FileField(help_text='只能上传pdf格式的文件。', storage=tlog.models.OverwriteStorage(), upload_to=tlog.models.user_dierctory_path, verbose_name='文件')),
                ('module_list', models.CharField(choices=[('ModuleA', 'A模块: ServerClient'), ('ModuleB', 'B模块: Network'), ('ModuleC', 'C模块: Python'), ('ModuleD', 'D模块: TroubleShooting'), ('ModuleE', 'E模块: English'), ('Other', 'Other')], default='ModuleA', max_length=100, verbose_name='模块')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'ordering': ('-log_date', '-uploaded_date'),
            },
        ),
    ]
