# Generated by Django 4.0.3 on 2022-03-21 06:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tlog', '0003_loguploadmodel_user_alter_loguploadmodel_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loguploadmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TlogEvaluate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluate_score', models.IntegerField(default=0, verbose_name='评分')),
                ('evaluate_comment', models.CharField(default='', max_length=100, verbose_name='评论')),
                ('evaluate_date', models.DateField(default=datetime.date.today, verbose_name='评价日期')),
                ('evaluate_coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评价教练')),
                ('tlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tlog.loguploadmodel')),
            ],
        ),
    ]
