# Generated by Django 4.0.3 on 2022-03-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlog', '0004_alter_loguploadmodel_user_tlogevaluate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlogevaluate',
            name='evaluate_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='评价日期'),
        ),
    ]
