# Generated by Django 4.0.3 on 2022-03-21 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlog', '0005_alter_tlogevaluate_evaluate_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tlogevaluate',
            old_name='evaluate_comment',
            new_name='evaluate_content',
        ),
        migrations.RenameField(
            model_name='tlogevaluate',
            old_name='evaluate_date',
            new_name='evaluate_time',
        ),
    ]
